### ISSUE TITLE
Il manque des classes

### ISSUE THREAD

**Issue by rilent** [robin57/m2giMetzCL#2]
@Leclouerec le projet est incompilable pour le moment, tu as oublié de commit ton CORSingleton que tu appeles dans ChatClient.

**Comment by Leclouerec** [comment]
Effectivement, je regarde

**Comment by rilent** [comment]
Merci, si tu commites, pense à pull mes changements, et à décommenter ce que j'ai mis dans ChatClient.java

Note : Dans le ChatClient.java ligne 48, vous avez mis en commentaire l'appel à openConnection(), du coup le client se connecte pas, je sais pas si c'est censé être remplacé par autre chose que tu n'as pas commit non plus?

**Comment by rilent** [comment]
Je fais mon relou mais je viens de voir que tu as crée une branche encore et sans faire de git pull du projet, donc t'as pas mon dernier commit par exemple, alors je voulais passer un petit message :

**IMPORTANT : Arretez de créer des branches sans faire de git pull avant svp, et quand vous avez fini votre dev, il faut merge le bordel et tout ramener sur la branche master, sinon on va avoir 36 branches à des états différents... et 0 chance que ça fonctionne.**

**Comment by raph312** [comment]
Ou sinon vous pouvez arrêter de travailler sur la master et garder cette branche pour un truc qui marche. Dans tous les cas ça fonctionnera pas

**Comment by raph312** [comment]
Si personne ne fais les merge correctement
